### ISSUE TITLE
TypeError: '>=' not supported between instances of 'AssertionError' and 'int'

### ISSUE THREAD

**Issue by linhcentrio** [yerfor/MimicTalk#39]
```
(/home/MimicTalk/venv) [root@aiclip-dfl2 MimicTalk]# **python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/VIDEO_003_cropped_25fps.mp4**
2024-11-29 20:08:29.274455: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732928909.309845  157782 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732928909.320264  157782 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
todo videos number: 1
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1732928912.743135  157782 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1732928912.856416  157894 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 565.57.01), renderer: NVIDIA RTX A4000/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1732928912.913155  157910 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
/home/MimicTalk/venv/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024.
  graph_config = self._runner.get_graph_config()
| Extracting Segmaps && Saving...
generating segment images in single-process...: 0it [00:00, ?it/s]
| Extracted Segmaps Done.
| Extracting background...
<class 'AssertionError'>
Traceback (most recent call last):
  File "/home/MimicTalk/data_gen/utils/process_video/extract_segment_imgs.py", line 365, in extract_segment_job
    bg_img = extract_background(img_lst, segmap_mask_lst, method=background_method, device=device, mix_bg=mix_bg)
  File "/home/MimicTalk/data_gen/utils/process_video/extract_segment_imgs.py", line 78, in extract_background
    assert len(img_lst) > 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/MimicTalk/data_gen/utils/process_video/extract_segment_imgs.py", line 495, in <module>
    extract_job(*fn_args[0])
  File "/home/MimicTalk/data_gen/utils/process_video/extract_segment_imgs.py", line 388, in extract_segment_job
    traceback.print_exc(e)
  File "/home/MimicTalk/venv/lib/python3.9/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/home/MimicTalk/venv/lib/python3.9/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/home/MimicTalk/venv/lib/python3.9/traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "/home/MimicTalk/venv/lib/python3.9/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'AssertionError' and 'int'
```

**Comment by selifecn** [comment]
背景图片没有生成成功，可以检查一下你的bg_imgs这个目录有没有成功建立...
