### ISSUE TITLE
error when train model "malloc(): unaligned tcache chunk detected"

### ISSUE THREAD

**Issue by linhcentrio** [yerfor/MimicTalk#6]
cp checkpoints/mimictalk_orig/os_secc2plane_torso/config.yaml checkpoints_mimictalk/TED_001_cropped_25fps
Traceback (most recent call last):
  File "/home/MimicTalk/inference/app_mimictalk.py", line 66, in train_once_args
    trainer = LoRATrainer(inp)
  File "/home/MimicTalk/inference/train_mimictalk_on_a_video.py", line 56, in __init__
    with open(os.path.join(self.inp['work_dir'], 'config.yaml'), "a") as f:
NotADirectoryError: [Errno 20] Not a directory: 'checkpoints_mimictalk/TED_001_cropped_25fps/config.yaml'
Training ERROR: [Errno 20] Not a directory: 'checkpoints_mimictalk/TED_001_cropped_25fps/config.yaml'
cp checkpoints/mimictalk_orig/os_secc2plane_torso/config.yaml checkpoints_mimictalk/TED_001_cropped_25fps
Traceback (most recent call last):
  File "/home/MimicTalk/inference/app_mimictalk.py", line 66, in train_once_args
    trainer = LoRATrainer(inp)
  File "/home/MimicTalk/inference/train_mimictalk_on_a_video.py", line 56, in __init__
    with open(os.path.join(self.inp['work_dir'], 'config.yaml'), "a") as f:
NotADirectoryError: [Errno 20] Not a directory: 'checkpoints_mimictalk/TED_001_cropped_25fps/config.yaml'
Training ERROR: [Errno 20] Not a directory: 'checkpoints_mimictalk/TED_001_cropped_25fps/config.yaml'
cp checkpoints/mimictalk_orig/os_secc2plane_torso/config.yaml checkpoints_mimictalk/TED_001_cropped_25fps
Traceback (most recent call last):
  File "/home/MimicTalk/inference/app_mimictalk.py", line 66, in train_once_args
    trainer = LoRATrainer(inp)
  File "/home/MimicTalk/inference/train_mimictalk_on_a_video.py", line 56, in __init__
    with open(os.path.join(self.inp['work_dir'], 'config.yaml'), "a") as f:
NotADirectoryError: [Errno 20] Not a directory: 'checkpoints_mimictalk/TED_001_cropped_25fps/config.yaml'
Training ERROR: [Errno 20] Not a directory: 'checkpoints_mimictalk/TED_001_cropped_25fps/config.yaml'
cp checkpoints/mimictalk_orig/os_secc2plane_torso/config.yaml checkpoints_mimictalk/TED_001_cropped_25fps
| WARN: checkpoints/mimictalk_orig/os_secc2plane_torso/secc_img2plane.yaml not exist.
lora_args_secc2plane:  {'lora_mode': 'secc2plane_sr', 'lora_r': 2}
lora_args_sr:  {'lora_mode': 'secc2plane_sr', 'lora_r': 2}
| load 'model' from 'checkpoints/mimictalk_orig/os_secc2plane_torso/model_ckpt_steps_100000.ckpt', strict=False
| model Trainable Parameters: 0.091M
| Copying video to data/raw/videos/TED_001_cropped_25fps.mp4
| ffmpeg -i /tmp/gradio/fd9eccf8c268498e23a00783ad7b11ef09d3f57d6fb39540899e119da547da83/TED_001_cropped_25fps.mp4 -vf fps=25,scale=w=512:h=512 -qmin 1 -q:v 1 -y data/raw/videos/TED_001_cropped_25fps.mp4
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 11 (GCC)
  configuration: --prefix=/usr/local --enable-shared --enable-avresample --enable-pic --disable-asm --disable-debug --disable-cuda --disable-cuvid
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/gradio/fd9eccf8c268498e23a00783ad7b11ef09d3f57d6fb39540899e119da547da83/TED_001_cropped_25fps.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.13.100
    comment         : Downloaded using YoutubeDownloader (https://github.com/Tyrrrz/YoutubeDownloader)
                    : Video: 3 Steps of Anxiety Overload – And How You Can Take Back Control @TED #shorts #ted
                    : Video URL: https://www.youtube.com/watch?v=n16B_4eMzSY
                    : Channel: TED
                    : Channel URL: https://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug
    description     : Lisa Damour explains why intense feelings -- including negative ones -- are an inevitable part of life, and how we can better understand them. Watch her full TED Talk: https://youtu.be/oITW0XsZd3o
  Duration: 00:00:59.05, start: 0.000000, bitrate: 602 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 512x512 [SAR 540:707 DAR 540:707], 468 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc60.27.100 libx264
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[mpeg4 @ 0x1c22db0] Invalid pixel aspect ratio 540/707, limit is 255/255 reducing
Output #0, mp4, to 'data/raw/videos/TED_001_cropped_25fps.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    description     : Lisa Damour explains why intense feelings -- including negative ones -- are an inevitable part of life, and how we can better understand them. Watch her full TED Talk: https://youtu.be/oITW0XsZd3o
    comment         : Downloaded using YoutubeDownloader (https://github.com/Tyrrrz/YoutubeDownloader)
                    : Video: 3 Steps of Anxiety Overload – And How You Can Take Back Control @TED #shorts #ted
                    : Video URL: https://www.youtube.com/watch?v=n16B_4eMzSY
                    : Channel: TED
                    : Channel URL: https://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 512x512 [SAR 97:127 DAR 97:127], q=1-31, 200 kb/s, SAR 540:707 DAR 540:707, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc58.18.100 mpeg4
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc58.18.100 aac
frame= 1476 fps=288 q=1.0 Lsize=   27189kB time=00:00:59.04 bitrate=3772.1kbits/s speed=11.5x
video:26229kB audio:921kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.144513%
[aac @ 0x1c255a0] Qavg: 1463.292
| Copy source video into work dir: checkpoints_mimictalk/TED_001_cropped_25fps
| Pre-extracted head_imgs not found, try to extract and save to data/processed/videos/TED_001_cropped_25fps/head_imgs, this may take a while...
| ffmpeg -i data/raw/videos/TED_001_cropped_25fps.mp4 -vf fps=25,scale=w=512:h=512 -qmin 1 -q:v 1 -start_number 0 -y data/processed/videos/TED_001_cropped_25fps/gt_imgs/%08d.jpg
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 11 (GCC)
  configuration: --prefix=/usr/local --enable-shared --enable-avresample --enable-pic --disable-asm --disable-debug --disable-cuda --disable-cuvid
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'data/raw/videos/TED_001_cropped_25fps.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.12.100
    comment         : Downloaded using YoutubeDownloader (https://github.com/Tyrrrz/YoutubeDownloader)
                    : Video: 3 Steps of Anxiety Overload – And How You Can Take Back Control @TED #shorts #ted
                    : Video URL: https://www.youtube.com/watch?v=n16B_4eMzSY
                    : Channel: TED
                    : Channel URL: https://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug
    description     : Lisa Damour explains why intense feelings -- including negative ones -- are an inevitable part of life, and how we can better understand them. Watch her full TED Talk: https://youtu.be/oITW0XsZd3o
  Duration: 00:00:59.07, start: 0.000000, bitrate: 3770 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 512x512 [SAR 97:127 DAR 97:127], 3639 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x237f140] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'data/processed/videos/TED_001_cropped_25fps/gt_imgs/%08d.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    description     : Lisa Damour explains why intense feelings -- including negative ones -- are an inevitable part of life, and how we can better understand them. Watch her full TED Talk: https://youtu.be/oITW0XsZd3o
    comment         : Downloaded using YoutubeDownloader (https://github.com/Tyrrrz/YoutubeDownloader)
                    : Video: 3 Steps of Anxiety Overload – And How You Can Take Back Control @TED #shorts #ted
                    : Video URL: https://www.youtube.com/watch?v=n16B_4eMzSY
                    : Channel: TED
                    : Channel URL: https://www.youtube.com/channel/UCAuUUnT6oDeKwE6v1NGQxug
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 512x512 [SAR 97:127 DAR 97:127], q=1-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame= 1476 fps=313 q=1.0 Lsize=N/A time=00:00:59.04 bitrate=N/A speed=12.5x
video:64401kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
| python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/TED_001_cropped_25fps.mp4
todo videos number: 1
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729091569.948328  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.042373  826820 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 560.35.03), renderer: NVIDIA RTX A4000/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1729091570.133811  826823 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
/home/MimicTalk/venv/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024.
  graph_config = self._runner.get_graph_config()
| Extracting Segmaps && Saving...
generating segment images in multi-processes...:   0%|                                                                                                                                                              | 0/1476 [00:00<?, ?it/s]
I0000 00:00:1729091570.655767  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.659714  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
I0000 00:00:1729091570.667124  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.670388  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.670669  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.679013  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.685722  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.687689  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.687877  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
I0000 00:00:1729091570.699897  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.705784  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
I0000 00:00:1729091570.711519  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
I0000 00:00:1729091570.714948  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
I0000 00:00:1729091570.715908  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729091570.716230  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
I0000 00:00:1729091570.721020  826730 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected
malloc(): unaligned tcache chunk detected

**Comment by yerfor** [comment]
Hi, it seems to be a error caused by mediapipe selfie segmentation. We used CUDA-based mediapipe. But it seems that you are using openGL-based mediapipe.

**Comment by mulanlew** [comment]
Is there a solution for this? I am not an admin on the cluster that I work on. However, I tried downloading the GPU version of TF through pip and conda and I was unable to solve it. Also, tensorflow is commented out in the requirements.txt for the installation of this project, which is what led me too this error in the first place.

**Comment by linhcentrio** [comment]
![image](https://github.com/user-attachments/assets/69e6bea9-7ab8-4544-8892-1b5a4152b8eb)
it's stll can be run with "Created TensorFlow Lite XNNPACK delegate for CPU.". How can i install mediapipe with fully support CUDA?

**Comment by zhanghongyong123456** [comment]
> Is there a solution for this? I am not an admin on the cluster that I work on. However, I tried downloading the GPU version of TF through pip and conda and I was unable to solve it. Also, tensorflow is commented out in the requirements.txt for the installation of this project, which is what led me too this error in the first place.

have you solve it

**Comment by cr7Por** [comment]
edit data_gen/utils/process_video/extract_segment_imgs.py line349, change if multiprocess_enable: to if False:

**Comment by SohailaAbobakr** [comment]
After training, I got the following output file instead of the expected checkpoint file: checkpoints_mimictalk/myImage/events.out.tfevents.1734004296.neptune.88832.0
Do you know why this is happening? I expected a .ckpt file to be generated for saving the model state.
Note This issue occurred specifically when I used images for training only.

**Comment by dkw-wkd** [comment]
train_mimictalk_on_a_video.py 

if self.torso_mode:
if self.ds['com_imgs'][di] is None:
img_name = f'data/processed/videos/{video_id}/com_imgs/{format(di, "08d")}.jpg'
img = torch.tensor(cv2.imread(img_name)[..., ::-1] / 127.5 - 1).permute(2,0,1).float() # [3, H, W]
self.ds['com_imgs'][di] = img

how to deal with this bug, 
are com_imgs head_imgs gt_imgs same?
